### ISSUE TITLE
Problem with the java API compilation on Ubuntu

### ISSUE THREAD

**Issue by Oelth** [insideout10/stanbol-freeling#2]
Hi everybody,
I'm currently trying to create the Java API for Freeling in order to use it on Stanbol.
In this way, I followed all the instructions given by the Freeling documentation without success. It seems to be a problem with my JDK but I really don't know how to fix it. 
This is what I've done :

Step A, compile Freeling in C++ (no problem here):

1)  Install the following packages (with "sudo apt-get install") :
- build-essential
- zlib1g-dev
- libboost1.48-all-dev
- automake
- autoconf
- libtool
- libboost-regex-dev
- libicu-dev
- libboost-filesystem-dev
- libboost-program-options-dev
- swig

2) Download the latest version of Freeling:
svn checkout http://devel.cpl.upc.edu/freeling/svn/tr
unk Freeling

3) Prepare my Freeling repository:
cd myfreeling
aclocal; libtoolize; autoconf; automake -a

4) Build and install Freeling:
./configure
make
sudo make install

Step B, compile the Java API (my problem is in this step):

1) Replace the freeling.i located to freeling/APIs/common/freeling.i by the freeling.i given at : [url]https://raw.github.com/ziodave/freeling-brew-formula/master/APIs/common/freeling.i[/url]

2) Set the parameters for the Makefile located to freeling/APIs/java/MakeFile

My Makefile is the following :

```
# Change these paths to match your installation
# Alternatively, you can call 'make' overriding variable values, E.g.:
#     make FREELINGDIR=/my/freeling/dir SWIGDIR=/my/swig/dir JAVADIR=/my/java/dir

FREELINGDIR = /home/saturn/freeling
SWIGDIR = /usr/share/swig2.0
JAVADIR = /usr/lib/jvm/jdk1.7.0_25

# you may change the package name if you want
PACKAGE = edu/upc/freeling
JPACKAGE = edu.upc.freeling

# Change your compiler, if necessary.
GCC=g++

all: freeling_javaAPI.cxx libfreeling_javaAPI.so

.PHONY: all

# Compile the C++ API
libfreeling_javaAPI.so: freeling_javaAPI.cxx
    $(GCC) -shared -o libfreeling_javaAPI.so freeling_javaAPI.cxx -lfreeling -L$(FREELINGDIR)/lib -I$(FREELINGDIR)/include -I$(JAVADIR)/include -I$(JAVADIR)/include/linux -fPIC
    $(JAVADIR)/bin/javac $(PACKAGE)/*.java
    $(JAVADIR)/bin/jar -cf freeling.jar $(PACKAGE)

# Build the Java JNI wrapper classes.
freeling_javaAPI.cxx: freeling_javaAPI.i ../common/freeling.i
    rm -rf $(PACKAGE)
    mkdir -p $(PACKAGE)
    swig -java -c++ -package $(JPACKAGE) -outdir $(PACKAGE) -o freeling_javaAPI.cxx -I$(SWIGDIR)/java -I$(SWIGDIR)/std -I$(SWIGDIR) freeling_javaAPI.i

clean:
    rm -rf *.jar *.so *.cxx *.class edu
    java -> $(JAVADIR)/bin/java
    jar -> $(JAVADIR)/bin/jar
```

3) Run make

And I get the following result :

```
g++ -shared -o libfreeling_javaAPI.so freeling_javaAPI.cxx -lfreeling -L/usr/local/share/freeling/lib -I/usr/local/share/freeling/include -I/usr/lib/jvm/jdk1.7.0_25/include -I/usr/lib/jvm/jdk1.7.0_25/include/linux -fPIC


freeling_javaAPI.cxx: In function ‘jlong Java_edu_upc_freeling_freelingJNI_new_1TreeIteratorNode_1_1SWIG_10(JNIEnv*, jclass)’:
freeling_javaAPI.cxx:2995:3: error: ‘tree_iterator’ was not declared in this scope
freeling_javaAPI.cxx:2995:3: note: suggested alternative:
/usr/local/include/freeling/tree.h:47:7: note:   ‘freeling::tree_iterator’
freeling_javaAPI.cxx:2995:18: error: ‘node’ was not declared in this scope
freeling_javaAPI.cxx:2995:18: note: suggested alternative:
/usr/local/include/freeling/morfo/language.h:372:14: note:   ‘freeling::node’
freeling_javaAPI.cxx:2995:23: error: ‘tree’ was not declared in this scope
freeling_javaAPI.cxx:2995:23: note: suggested alternative:
/usr/local/include/freeling/tree.h:35:26: note:   ‘freeling::tree’
freeling_javaAPI.cxx:2995:36: error: expected primary-expression before ‘>’ token
freeling_javaAPI.cxx:2995:39: error: ‘result’ was not declared in this scope
freeling_javaAPI.cxx:2999:46: error: expected primary-expression before ‘>’ token
freeling_javaAPI.cxx:2999:49: error: expected primary-expression before ‘)’ token
freeling_javaAPI.cxx:2999:50: error: expected ‘;’ before ‘new’
freeling_javaAPI.cxx:3000:38: error: expected primary-expression before ‘>’ token
freeling_javaAPI.cxx:3000:42: error: expected primary-expression before ‘)’ token
freeling_javaAPI.cxx: In function ‘jlong Java_edu_upc_freeling_freelingJNI_new_1TreeIteratorNode_1_1SWIG_11(JNIEnv*, jclass, jlong, jobject)’:
freeling_javaAPI.cxx:3007:3: error: ‘tree’ was not declared in this scope
freeling_javaAPI.cxx:3007:3: note: suggested alternative:
/usr/local/include/freeling/tree.h:35:26: note:   ‘freeling::tree’
freeling_javaAPI.cxx:3007:9: error: ‘node’ was not declared in this scope
freeling_javaAPI.cxx:3007:9: note: suggested alternative:
/usr/local/include/freeling/morfo/language.h:372:14: note:   ‘freeling::node’
freeling_javaAPI.cxx:3007:17: error: ‘arg1’ was not declared in this scope
freeling_javaAPI.cxx:3007:39: error: expected primary-expression before ‘)’ token
freeling_javaAPI.cxx:3007:41: error: expected ‘;’ before numeric constant
freeling_javaAPI.cxx:3008:3: error: ‘tree_iterator’ was not declared in this scope
freeling_javaAPI.cxx:3008:3: note: suggested alternative:
/usr/local/include/freeling/tree.h:47:7: note:   ‘freeling::tree_iterator’
freeling_javaAPI.cxx:3008:36: error: expected primary-expression before ‘>’ token
freeling_javaAPI.cxx:3008:39: error: ‘result’ was not declared in this scope
freeling_javaAPI.cxx:3013:27: error: expected primary-expression before ‘)’ token
freeling_javaAPI.cxx:3014:46: error: expected primary-expression before ‘>’ token
freeling_javaAPI.cxx:3014:49: error: expected primary-expression before ‘)’ token
freeling_javaAPI.cxx:3014:50: error: expected ‘;’ before ‘new’
freeling_javaAPI.cxx:3015:38: error: expected primary-expression before ‘>’ token
freeling_javaAPI.cxx:3015:42: error: expected primary-expression before ‘)’ token
freeling_javaAPI.cxx: In function ‘jlong Java_edu_upc_freeling_freelingJNI_new_1TreeIteratorNode_1_1SWIG_12(JNIEnv*, jclass, jlong, jobject)’:
freeling_javaAPI.cxx:3022:3: error: ‘tree_iterator’ was not declared in this scope
freeling_javaAPI.cxx:3022:3: note: suggested alternative:
/usr/local/include/freeling/tree.h:47:7: note:   ‘freeling::tree_iterator’
[...]
freeling_javaAPI.cxx:12474:3: error: ‘lang_ident’ was not declared in this scope
freeling_javaAPI.cxx:12474:3: note: suggested alternative:
/usr/local/include/freeling/morfo/lang_ident.h:55:14: note:   ‘freeling::lang_ident’
freeling_javaAPI.cxx:12474:15: error: ‘arg1’ was not declared in this scope
freeling_javaAPI.cxx:12474:35: error: expected primary-expression before ‘)’ token
freeling_javaAPI.cxx:12474:37: error: expected ‘;’ before numeric constant
freeling_javaAPI.cxx:12483:25: error: expected primary-expression before ‘)’ token
freeling_javaAPI.cxx:12511:16: error: expected ‘)’ before ‘const’
freeling_javaAPI.cxx:12511:120: error: expected ‘)’ before ‘;’ token
freeling_javaAPI.cxx: In function ‘jlong Java_edu_upc_freeling_freelingJNI_GenericIteratorNode_1SWIGUpcast(JNIEnv*, jclass, jlong)’:
freeling_javaAPI.cxx:12519:7: error: ‘tree_iterator’ was not declared in this scope
freeling_javaAPI.cxx:12519:7: note: suggested alternative:
/usr/local/include/freeling/tree.h:47:7: note:   ‘freeling::tree_iterator’
freeling_javaAPI.cxx:12519:22: error: ‘node’ was not declared in this scope
freeling_javaAPI.cxx:12519:22: note: suggested alternative:
/usr/local/include/freeling/morfo/language.h:372:14: note:   ‘freeling::node’
freeling_javaAPI.cxx:12519:27: error: ‘tree’ was not declared in this scope
freeling_javaAPI.cxx:12519:27: note: suggested alternative:
/usr/local/include/freeling/tree.h:35:26: note:   ‘freeling::tree’
freeling_javaAPI.cxx:12519:40: error: expected primary-expression before ‘>’ token
freeling_javaAPI.cxx:12519:44: error: expected primary-expression before ‘)’ token
freeling_javaAPI.cxx:12519:58: error: ‘generic_iterator’ was not declared in this scope
freeling_javaAPI.cxx:12583:25: error: expected primary-expression before ‘)’ token
freeling_javaAPI.cxx:12583:39: error: ‘dep_tree’ was not declared in this scope
freeling_javaAPI.cxx:12583:39: note: suggested alternative:
/usr/local/include/freeling/morfo/language.h:478:14: note:   ‘freeling::dep_tree’
freeling_javaAPI.cxx:12583:50: error: expected primary-expression before ‘)’ token
make: *** [libfreeling_javaAPI.so] Error 1
```

I tried to change my JDK with older versions (I tried with JDK7, JDK6 and SDK6) but the result is the same.

For information I'm working in a virtual machine with Ubuntu12.04 x64, I also tried to compile Freeling with Ubuntu12.04 x32 but the result is the same.

I added the following lines on my .bashrc : 

```
JAVA_HOME=/usr/lib/jvm/jdk1.7.0_25
MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=2048m"
JAVA_OPTS="-Xmx2048m -XX:MaxPermSize=2048m"
ANT_OPTS="-Xmx2048m -XX:MaxPermSize=2048m"
JVM_ARGS="-Xmx2048m -XX:MaxPermSize=2048m"
export MAVEN_OPTS
export JAVA_OPTS
export ANT_OPTS
export JVM_ARGS
export JAVA_HOME
```

I think I'm doing something wrong but I really don't know what, I spent 4 days to find a solution without success. Could someone help me ?

Thank you in advance !
